### ISSUE TITLE
Hi Sir, I can see you are akka expert. Can you help solve my issue please?

### ISSUE THREAD

**Issue by pranavkapoorr** [hseeberger/welcome-akka-typed#1]
Hi sir

Apologies to reach you like this. Can you help me with the issue listed below:

https://github.com/pranavkapoorr/AltaPay-Link_Service/issues/1#issue-366608337

Kindly have a look please.

Many thanks in advance

Pranav

**Comment by hseeberger** [comment]
This is just a demo open source project, not a commercial service offering.

**Comment by pranavkapoorr** [comment]
I understand, but I gave the kink to my issue to which I believe you could be helpful. Did you have a look at it?
